apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: swagger-petstore
  annotations:
    github.com/project-slug: ameer-hcl/swagger-petstore
spec:
  type: other
  lifecycle: unknown
  owner: team-a
